### ISSUE TITLE
Feature Suggestion: Loading Screen Progress

### ISSUE THREAD

**Issue by celabgalactic** [mhebrard/nms-browser#19]
Provide some indication of activity progressing besides the rotating AGT logo.  If its not possible to show a percantage progress, then at least a running counter indicating number of records processed.  This will give users comfort something is happening.

**Comment by mhebrard** [comment]
It is not possible to display the number of records process.
the main waiting time is due to the connection to Google sheet and data transfer. Once the data is transfered, the processing is almost instant.

I added a message "please wait"
and the logo turning is the indicator that something is happening.
