### ISSUE TITLE
System Information Sidebar Data Population Issue

### ISSUE THREAD

**Issue by celabgalactic** [mhebrard/nms-browser#6]
A bug report here on AGT Navi:
Region observed: Louyen, Hilbert Dimension.

Observation: Some (not all) purple systems (inter-region systems) appear to show correct name on the map display, but the detailed pop up window seems to be picking up wrong data for some of the purple stars.

Example: Purple star display for AGT Nerimar (not louyen but nearby) with coordinates 0802:0086:0804:0134 is displaying correct name on map display but pulling up info for AGT Lexando, 0802:0086:0805:0134 (notice one address difference)
Some other purple stars display correct popup info

**Comment by mhebrard** [comment]
Cannot confirm the example, but the issue of wrong info displayed in the infobox should be fixed in v0.5.0
Problem was that on click, system info was query based on SSI, and in a context of multiple regions displayed, multiple system will match the same SSI.
In v0.5.0, the query of system is based on glyph code that is unique witin one galaxy
